kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
  name: system-storage
  namespace: ms-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp2
  volumeMode: Filesystem
