apiVersion: v1
kind: PersistentVolume
metadata:
  name: my_iu_pv
spec:
  capacity:
    storage: 2Gi 
  accessModes:
  - ReadWriteMany 
  nfs:
    server: 10.19.137.80
    path: /var/mynfs-data/pv-iu-01
  persistentVolumeReclaimPolicy: Recycle  
