apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: example-configmap-snippet
spec:
  targetResource:
    apiVersion: v1
    kind: ConfigMap
  title: configmap-example-snippet
  description: An example Job YAML sample code
  snippet: true
  yaml: |
    # Configuration values can be set as key-value properties
    database: mongodb
    database_uri: mongodb://localhost:27017
    
    # Or set as complete file contents (even JSON!)
    keys: | 
      image.public.key=771 
      rsa.public.key=42
