apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: edge-any-interconnect
  namespace: ms-test
spec:
  # Add fields here
  deploymentPlan:
    image: quay.io/interconnectedcloud/qdrouterd:1.7.0
    role: edge
    size: 3
    placement: Every    #Any/Every/AntiAffinity/Node
